#!/bin/bash
#cmd arg: <jar> <Xmx>
#env arg: [JAVA_BIN]

shell_dir=$(cd $(dirname $0); pwd)
if [[ "$OMSLS_GC_FLAGS" == "" ]]; then
  export OMSLS_GC_FLAGS=$shell_dir/flags/zgc.txt
fi

$shell_dir/omsls $1 $2
