#!/bin/bash

if [[ "$JAVA_BIN" == "" ]]; then
  JAVA_BIN=java
fi

JAVA_OPTS="-XX:+UseTransparentHugePages "

if [[ "$OMSLS_JAVA8" == "1" ]]; then
  if [[ "$OMSLS_YGGDRASIL_FLAGS" == "" ]]; then export OMSLS_YGGDRASIL_FLAGS="$(cd $(dirname $0); pwd)/flags/yggdrasil_null.txt"; fi
  JAVA_OPTS="$(<$OMSLS_GC_FLAGS) $(<$OMSLS_YGGDRASIL_FLAGS) $JAVA_OPTS $OMSLS_OPTS"
else
  JAVA_OPTS="@$OMSLS_GC_FLAGS $OMSLS_YGGDRASIL_FLAGS $JAVA_OPTS $OMSLS_OPTS"
fi

#echo JAVA_OPTS=$JAVA_OPTS
export OMSLS_GC_FLAGS=
export OMSLS_YGGDRASIL_FLAGS=
export OMSLS_OPTS=
$JAVA_BIN -Xms$2 -Xmx$2 $JAVA_OPTS -jar $1 --nogui
