#!/bin/bash
#cmd arg: <jar> <Xmx>
#env arg: [JAVA_BIN]

shell_dir=$(cd $(dirname $0); pwd)
corrected_mem=$2
if [[ "$OMSLS_GC_FLAGS" == "" ]]; then
  mem_unit=${2:0-1:1}
  mem_amount=${2%$mem_unit}
  
  export OMSLS_GC_FLAGS=$shell_dir/flags/g1gc.txt
  if [[ "${mem_unit^}" == "G" ]]; then
    if [[ $mem_amount -gt 12 ]]; then    export OMSLS_GC_FLAGS=$shell_dir/flags/g1gc.higher.txt; fi
  fi
  if [[ "${mem_unit^}" == "M" ]]; then
    if [[ $mem_amount -gt 12000 ]]; then export OMSLS_GC_FLAGS=$shell_dir/flags/g1gc.higher.txt; fi
    if [[ $mem_amount -lt 250 ]]; then
      corrected_mem=250M
    fi
  fi
fi
if [[ "$OMSLS_JAVA8" == "" ]]; then export OMSLS_JAVA8=1; fi

$shell_dir/omsls $1 $corrected_mem
